### ISSUE TITLE
documentation: docker swarm HA setup with TLS

### ISSUE THREAD

**Issue by dalu** [dgraph-io/dgraph#1790]
Being as lazy (and old and stupid) as I am I'm reading through https://docs.dgraph.io/deploy/
And since I have recently experimented with docker swarm and kubernetes and for the life of me I couldn't get kubernetes up and running (at least not without kubeadm which locks me out of the cluster because of lacking privileges).
So I'm wondering how would I run dgraph zero and dgraph client on a 3 node docker swarm cluster?
CockroachDB has a docker swarm setup tutorial that, well it kind of works but then again it doesn't.

Wouldn't it be nice if newcomers could just take a docker-compose.yml and apply it with `docker stack deploy -f dgraph-3-node-ha-stack.yml`

So what is the content of a docker stack recipe?
Essentially everything in the docker world.
- volumes
- secrets
- networks
- container names and params

https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/

So what is needed?
- dgraph zero with --replicas=3
- dgraph client?
- tls configuration , needs more explaining, system ca?

In general more explaining regarding the tls config is in order.
An example setup with tls enabled and also maybe a separate client auth via tls cert would be nice to have. It's not clear which options are needed for which kind of tls config.
For `tls.client_auth string` what kind of certificate is required? How is it generated, which extensions?

One could take inspiration from https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-docker-swarm.html

Meanwhile I'm experimenting and will post if I find anything out, this is also a learning experience for me.

**Comment by manishrjain** [comment]
Let's set up both docker swarm and Kubernetes config files for users to follow.

**Comment by dalu** [comment]
here's a docker-compose config that "works for me"

```
# docker-compose.yml
version: "3.4"
volumes:
  dgdz:
    driver: local
  dgds:
    driver: local
networks:
  default:
    driver: bridge
services:
  dgz:
    image: dgraph/dgraph:latest
    networks:
      - default
    volumes:
      - "dgdz:/dgraph"
    command: dgraph zero --bindall=true --my=dgz:7080
  dgs:
    image: dgraph/dgraph:latest
    ports:
      - "127.0.0.1:17080:7080"
      - "127.0.0.1:18080:8080"
      - "127.0.0.1:19080:9080"
    networks:
      - default
    volumes:
      - "dgds:/dgraph"
    command: dgraph server --my=dgs:7080 --zero=dgz:7080 --memory_mb=4096
```
run it with
`docker-compose up -d`
while  being in a directory where the docker-compose.yml file is present
preferrable name the directory `dg` or `dgraph`
e.g.
```
mkdir dg
cd dg
$EDITOR docker-compose.yml
docker-compse up -d
```

**Comment by dalu** [comment]
then, from the forum
docker swarm mode
with 3 zeroes and 3 servers

dgz.yml
```
version: "3.4"
volumes:
  dgdz1:
    driver: local
  dgdz2:
    driver: local
  dgdz3:
    driver: local
networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: ""
services:
  dgz1:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    networks:
      - default
    volumes:
      - "dgdz1:/dgraph"
    command: dgraph zero --bindall=true --my=dgz1:7080 --idx=1 --replicas=3 
  dgz2:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    networks:
      - default
    volumes:
      - "dgdz2:/dgraph"
    command: dgraph zero --bindall=true --my=dgz2:7080 --idx=2 --replicas=3 --peer dgz1:7080
  dgz3:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
    networks:
      - default
    volumes:
      - "dgdz3:/dgraph"
    command: dgraph zero --bindall=true --my=dgz3:7080 --idx=3 --replicas=3 --peer dgz1:7080
```

dgs.yml
```
version: "3.4"
volumes:
  dgds1:
    driver: local
  dgds2:
    driver: local
  dgds3:
    driver: local
networks:
  default:
    driver: overlay
    driver_opts:
      encrypted: ""
services:
  dgs1:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    ports:
      - "7080:7080"
      - "8080:8080"
      - "9080:9080"
    networks:
      - default
    volumes:
      - "dgds1:/dgraph"
    command: dgraph server --my=dgs1:7080 --zero=dgz1:7080 --memory_mb=2048
  dgs2:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    ports:
      - "7081:7081"
      - "8081:8081"
      - "9081:9081"
    networks:
      - default
    volumes:
      - "dgds2:/dgraph"
    command: dgraph server --my=dgs2:7081 --zero=dgz2:7080 --memory_mb=2048 --port_offset=1
  dgs3:
    image: dgraph/dgraph:latest
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 2G
    ports:
      - "7082:7082"
      - "8082:8082"
      - "9082:9082"
    networks:
      - default
    volumes:
      - "dgds3:/dgraph"
    command: dgraph server --my=dgs3:7082 --zero=dgz3:7080 --memory_mb=2048 --port_offset=2
```

**however tls config is missing**
