### ISSUE TITLE
Mutation with multiple deletions aborts

### ISSUE THREAD

**Issue by dpeek** [dgraph-io/dgraph#1958]
Run the following two mutations in Dgraph UI (running Dgraph 1.0.1)

```
{ set {
  _:node <typePerson> "" .
  _:node <__typename> "Person" .
  _:node <name> "Tim" .
  _:node <children> _:node0 .
  _:node0 <parents> _:node .
  _:node0 <typePerson> "" .
  _:node0 <__typename> "Person" .
  _:node0 <name> "Jerry" .
  _:node0 <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node0 <updatedAt> "2017-12-26T15:36:16.466Z" .
  _:node <children> _:node1 .
  _:node1 <parents> _:node .
  _:node1 <typePerson> "" .
  _:node1 <__typename> "Person" .
  _:node1 <name> "Olivia" .
  _:node1 <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node1 <updatedAt> "2017-12-26T15:36:16.466Z" .
  _:node <children> _:node2 .
  _:node2 <parents> _:node .
  _:node2 <typePerson> "" .
  _:node2 <__typename> "Person" .
  _:node2 <name> "Paul" .
  _:node2 <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node2 <updatedAt> "2017-12-26T15:36:16.466Z" .
  _:node <createdAt> "2017-12-26T15:36:16.466Z" .
  _:node <updatedAt> "2017-12-26T15:36:16.466Z" .
}}
```

Then (substituting `uids`)

```
{ delete {
  <node> <children> <node0> .
  <node0 > <parents> <node> .
  <node> <children> <node1> .
  <node1> <parents> <node> .
}}
```

**Comment by janardhan1993** [comment]
@dpeek : Can you also share your schema ?

**Comment by dpeek** [comment]
```
dob: dateTime @index(hour) .
lastActiveAt: dateTime @index(hour) .
name: string @index(exact,term) .
title: string @index(exact) .
employed: bool @index(bool) .
time: int @index(int) .
age: int @index(int) .
height: float @index(float) .
partner: uid .
children: uid .
parents: uid .
createdAt: dateTime @index(hour) .
updatedAt: dateTime @index(hour) .
```

**Comment by dpeek** [comment]
I'm running in docker with this `docker-compose.yml`:

```
version: '3'

services:
  zero:
    image: dgraph/dgraph:v1.0.1
    command: dgraph zero --port_offset -2000 --my=zero:5080
    restart: on-failure
    volumes:
      - dgraph:/dgraph
  server:
    image: dgraph/dgraph:v1.0.1
    command: dgraph server --my=server:7080 --memory_mb=2048 --zero=zero:5080
    restart: on-failure
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
  ui:
    image: dgraph/dgraph:v1.0.1
    command: dgraph-ratel
    restart: on-failure
    ports:
      - 8081:8081
volumes:
  dgraph:
```
