### ISSUE TITLE
Docker Compose configuration does not work on Windows 10

### ISSUE THREAD

**Issue by krishnakumarb** [dgraph-io/dgraph#1986]
* Doc page: [get-started/index.md](https://docs.dgraph.io/get-started/)
* Doc version: `release/v1.0.1`

The Docker Compose configuration listed on this page does not work for me on Windows 10 with Compose 1.17.1. It fails to start with the error `sync w: invalid argument`. The configuration that works for me on Windows 10 (1709) and macOS High Sierra is this:

```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraphvolume
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --port_offset -2000 --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraphvolume
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=server:7080 --memory_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraphvolume
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8081:8081
    command: dgraph-ratel

volumes:
  dgraphvolume:

```
