### ISSUE TITLE
Trouble setting up TLS authentication

### ISSUE THREAD

**Issue by ospaarmann** [dgraph-io/dgraph#2222]
I'm trying to get TLS authentication up and running locally with Docker compose. I'm currently writing an Elixir client and am stuck. This is not a bug but any help is greatly appreciated since the documentation is not that clear on how to proceed. So thank you for any hint in the right direction.

## Create a self-signed CA & client certificate with OpenSSL 
[(Source)](https://kb.op5.com/pages/viewpage.action?pageId=19073746#sthash.U20DJ3Bi.dpbs)

**Generate CA key & certificate** 
```
$ openssl genrsa -out MyRootCA.key 2048
$ openssl req -x509 -new -nodes -key MyRootCA.key -sha256 -days 1024 -out MyRootCA.pem
```

**Generate client key & certificate signing request**
I use 'localhost' as Common Name
```
$ openssl genrsa -out MyClient1.key 2048
$ openssl req -new -key MyClient1.key -out MyClient1.csr
```

**Generate client certificate based on our own CA certificate**

`$ openssl x509 -req -in MyClient1.csr -CA MyRootCA.pem -CAkey MyRootCA.key -CAcreateserial -out MyClient1.pem -days 1024 -sha256`

**We end up with:** 

```
MyClient1.csr
MyClient1.key
MyClient1.pem
MyRootCA.key
MyRootCA.pem
MyRootCA.srl
```

## Adapt docker-compose.yml

_(Please note: I create the certificates with openssl in ~/exdgraph/tls and then mount this as a volume into the Dgraph server container.)_

```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
      - ~/exdgraph/tls:/var/dgraph/tls
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=server:7080 --memory_mb=2048 --zero=zero:5080 --tls_on --tls_ca_certs=/var/dgraph/tls/MyRootCA.pem --tls_cert=/var/dgraph/tls/MyClient1.pem --tls_cert_key=/var/dgraph/tls/MyClient1.key --tls_client_auth=REQUIREANDVERIFY
  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  dgraph:
```

## Elixir Code to connect to Dgraph via gRPC

```elixir
def connect(_opts) do
  ca_path = "~/exdgraph/tls/MyClient1.pem"
  cred = GRPC.Credential.new(ssl: [cacertfile: ca_path])
  opts = [cred: cred]
  case GRPC.Stub.connect("localhost:9080", opts) do
    {:ok, channel} ->
      {:ok, channel}

    _ ->
      Logger.error("ExDgraph: Connection Failed")
      {:error, ExDgraph.Error}
      # TODO: Proper error handling
  end
end
```

**Error message when connecting / running tests:**
```

23:01:21.188 [error] ExDgraph: Connection Failed

23:01:21.189 [error] ExDgraph.Protocol (#PID<0.300.0>) failed to connect: ** (ErlangError) Erlang error: ExDgraph.Error

23:01:21.188 [info]  ['TLS', 32, 'client', 58, 32, 73, 110, 32, 115, 116, 97, 116, 101, 32, 'cipher', 32, 'received SERVER ALERT: Fatal - Bad Certificate', 10]


 11) test mutation/2 returns {:error, error} for incorrect mutation (MutationTest)
     test/mutation_test.exs:27
     ** (DBConnection.ConnectionError) connection not available because of disconnection
     stacktrace:
       (db_connection) lib/db_connection.ex:860: DBConnection.run/3
       (ex_dgraph) lib/exdgraph/operation.ex:19: ExDgraph.Operation.operation/2
       test/mutation_test.exs:10: MutationTest.__ex_unit_setup_0/1
       test/mutation_test.exs:1: MutationTest.__ex_unit__/2
```
