### ISSUE TITLE
unknown flag: --lru_mb

### ISSUE THREAD

**Issue by omurbekjk** [dgraph-io/dgraph#2318]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
`dgraph:latest`

- Have you tried reproducing the issue with latest release?

- What is the hardware spec (RAM, OS)?
`Ubuntu 16.04` 

- Steps to reproduce the issue (command/config used to run Dgraph).
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
```

- Expected behaviour and actual result.
It should work on my localhost:8080, But I am getting `dockercomposefiles_server_1 exited with code 1
server_1  | Error: unknown flag: --lru_mb
`
