### ISSUE TITLE
Getting rpc error: code = Unknown desc = Unable to find log file. Please retry continuously

### ISSUE THREAD

**Issue by akshaydeo** [dgraph-io/dgraph#2489]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
master (current)

- Have you tried reproducing the issue with latest release?
I am on the latest version

- What is the hardware spec (RAM, OS)?
```
            memory: "5120Mi"
            cpu: "1000m"
          limits:
            memory: "6144Mi"
            cpu: "1250m"
```

- Steps to reproduce the issue (command/config used to run Dgraph).
Nothing specific

- Expected behaviour and actual result.
This error intermittently keep on coming after series of mutations. It specifically happens for certain Quads, and keep on happening for those, at the same time other mutations keep on passing.

After digging in the code, I figured out this happens when some of the log files are garbage collected, this could happen. I tried retrying 5 times with exponential backoff, still does not work.
