### ISSUE TITLE
Basic read-after-write broken in transactions

### ISSUE THREAD

**Issue by adamglt** [dgraph-io/dgraph#2727]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
v1.0.10

- Have you tried reproducing the issue with latest release?
Yes

- Steps to reproduce the issue (command/config used to run Dgraph).
Running dgraph using `docker-compose`:
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v1.0.10
    volumes:
    - type: volume
      source: dgraph
      target: /dgraph
      volume:
        nocopy: true
    ports:
    - 5080:5080
    - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:v1.0.10
    volumes:
    - type: volume
      source: dgraph
      target: /dgraph
      volume:
        nocopy: true
    ports:
    - 8080:8080
    - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:v1.0.10
    volumes:
    - type: volume
      source: dgraph
      target: /dgraph
      volume:
        nocopy: true
    ports:
    - 8000:8000
    command: dgraph-ratel

volumes:
  dgraph:
```

and this snippet:
```
func main() {
	conn, err := grpc.Dial("localhost:9080", grpc.WithInsecure())
	if err != nil {
		panic(err)
	}
	defer conn.Close()

	dg := dgo.NewDgraphClient(api.NewDgraphClient(conn))
	txn := dg.NewTxn()

	mut, err := json.Marshal(map[string]string{"bla": "blabla", "hey": "heyhey"})
	if err != nil {
		panic(err)
	}
	_, err = txn.Mutate(context.TODO(), &api.Mutation{
		SetJson: mut,
	})
	if err != nil {
		panic(err)
	}

	res, err := txn.Query(context.TODO(), `query q1 { q(func: has(bla)) { bla hey } }`)
	if err != nil {
		panic(err)
	}

	fmt.Printf("%s", res.Json)
	txn.Discard(context.TODO())
}
```

- Expected behaviour and actual result.
Expected: the query should return the inserted node (this works in previous versions).
Actual: response is empty.

Seems like a pretty trivial read-after-write scenario for transaction tests, am I missing something?
