### ISSUE TITLE
Proper Docker support

### ISSUE THREAD

**Issue by romansky** [dgraph-io/dgraph#282]
I'm confused as to the official support for running `dgraph` inside a docker image, I see some discussions about how the official docker hub image is using version 0.3 of `dgraph`, and how according to https://wiki.dgraph.io/Beginners_Guide#Docker:_Deprecated starting version 0.4 usage of Docker is deprecated.. =/

For my development projects and production I like to have a deterministic way of creating a clean working environment, Docker is key to this (IMO).

Can you maybe provide more information of why its deprecated? or is it simply a matter of maintaining the Docker repo?

**Comment by pawanrawal** [comment]
Hey @romansky 

Before v0.3, we supported Docker because to build the Dgraph binary you had to compile RocksDB and all that could be done as part of the Dockerfile.

From v0.3 onwards, we have started releasing binaries for Dgraph, which have RocksDB embedded and are sufficient for running Dgraph. Hence Docker isn't of any use really. Also Dgraph creates directories for mutations, postings and uids from the directory within which you run the binary from. You can just delete those if you want to be back to a clean slate. 

Let us know if you still have questions about this.

**Comment by romansky** [comment]
Hi @pawanrawal, as a developer of `dgraph` your approach is understandable.
As a user, I would want a contained environment which I can easily grok the deployment / dependencies of a component in the system.
Docker allows me to explicitly express what directories are affected by this artifact I want to deploy, the ports which are open and any arguments which I provided to have the service running as I needed.

Consider this `docker-compose.yml` 
```
version: '2'
services:
  redis:
    image: redis:3.2
    ports:
     - "6379:6379"
  dgraph:
     image: dgraph
     ports:
      -  "8180:8080"
     volumes:
       - /data/dgraph:/dgraph
```
Hope the motivation for using Docker is clearer now.

**Comment by pawanrawal** [comment]
Thanks for mentioning your use case. I will get back to you with an update on this.

**Comment by romansky** [comment]
@pawanrawal great, thanks!

**Comment by pawanrawal** [comment]
Hey @romansky, we released a Docker image for `v0.4.4` of Dgraph which is the latest release.
You can find the instructions for using it https://wiki.dgraph.io/Beginners_Guide#Docker.

Would love to hear about your usage of Dgraph.

**Comment by romansky** [comment]
Thanks @pawanrawal, I'm evaluating it for storage of data generated from scraping & crawling.

**Comment by MichelDiz** [comment]
This work (but)
```yml
version: '3.3'
services:
  dgraph:
    image: dgraph/dgraph
    tty: true
    stdin_open: true
    working_dir: /dgraph
    ports:
      - '8080:8080'
      - '9080:9080'
    command: dgraph --bindall=true --memory_mb 2048

```
This doesn't - What I'm missing?
```
version: '3.3'
services:
  dgraph:
    image: dgraph/dgraph
    tty: true
    stdin_open: true
    volumes:
      - '.\dgraphPersiste:/dgraph'
    working_dir: /dgraph
    ports:
      - '8080:8080'
      - '9080:9080'
    command: dgraph --bindall=true --memory_mb 2048

```

**Comment by MichelDiz** [comment]
For now I created this yml just for my need. I need to access some folder to export nodes with 
`curl localhost:8080/admin/export
`
```yml
version: '3.3'
services:
  dgraph:
    image: dgraph/dgraph
    tty: true
    stdin_open: true
    volumes:
      - '/dgraph'
      - '.\dgraphexport:/dgraphexport'
    working_dir: /dgraph
    ports:
      - '8080:8080'
      - '9080:9080'
    command: dgraph --bindall=true --memory_mb 2048
```
