### ISSUE TITLE
Got invalid keyword: minweight at root

### ISSUE THREAD

**Issue by Firezyz** [dgraph-io/dgraph#3135]
I run my dgraph with 'docker-compose.yml' file
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=4096 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  dgraph:
```

- What is the hardware spec (RAM, OS)?
```mac os 10.14.2```

I start dgraph with this command`docker-compose up -d`

I want use 'K-Shortest Path Queries' , but when I run 
`{
 path as shortest(from: 0xb19, to: 0xa98, minweight: 1) {
  goto
 }
 path(func: uid(path)) {
   name
 }
}`
I got this error`Got invalid keyword: minweight at root`
