### ISSUE TITLE
SIGSEGV in v1.0.14 acl

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/dgraph#3401]
**tl;dr**
`dgraph acl info -d=localhost:9080 -u alice` dies of SIGTERM in v1.0.14 on mac.

Steps to reproduce:

`docker-compose up` and in another tab:
```
paul ratel 𝝺 dgraph acl info -d=localhost:9080 -u alice
I0513 15:59:03.886898   64060 run_ee.go:207] Running transaction with dgraph endpoint: localhost:9080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x457b63d]

goroutine 1 [running]:
github.com/dgraph-io/dgraph/ee/acl.info(0xc0001510e0, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/ee/acl/run_ee.go:254 +0x12ad
github.com/dgraph-io/dgraph/ee/acl.initSubcommands.func8(0xc000213440, 0xc0004f2a80, 0x0, 0x3)
	/ext-go/1/src/github.com/dgraph-io/dgraph/ee/acl/run_ee.go:186 +0x32
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute(0xc000213440, 0xc0004f29f0, 0x3, 0x3, 0xc000213440, 0xc0004f29f0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702 +0x2d3
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x5529380, 0x5, 0x0, 0x0)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783 +0x2dc
github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute(0x5529380, 0x403371d, 0x547740c)
	/ext-go/1/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736 +0x2b
github.com/dgraph-io/dgraph/dgraph/cmd.Execute()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:60 +0x3b
main.main()
	/ext-go/1/src/github.com/dgraph-io/dgraph/dgraph/main.go:33 +0x88
```

```
paul ratel 𝝺 dgraph help

Dgraph is a horizontally scalable and distributed graph database,
providing ACID transactions, consistent replication and linearizable reads.
It's built from ground up to perform for a rich set of queries. Being a native
graph database, it tightly controls how the data is arranged on disk to optimize
for query performance and throughput, reducing disk seeks and network calls in a
cluster.

Dgraph version   : v1.0.14
Commit SHA-1     : 26cb2f94
Commit timestamp : 2019-04-12 13:21:56 -0700
Branch           : HEAD
Go version       : go1.11.5
```

**docker-compose.yml**
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v1.0.14
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:v1.0.14
    volumes:
      - type: volume
        source: dgraph
        target: /dgraph
        volume:
          nocopy: true
      - ./acl-secret.txt:/acl-secret.txt
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080 --enterprise_features --hmac_secret_file=/acl-secret.txt
```
