### ISSUE TITLE
Error while creating badger KV posting store error: unexpected end of JSON input

### ISSUE THREAD

**Issue by liu1000** [dgraph-io/dgraph#3669]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
1.0.15

- Have you tried reproducing the issue with latest release?
yes, 1.0.16

- What is the hardware spec (RAM, OS)?
16G RAM, CentOS 7

- Steps to reproduce the issue (command/config used to run Dgraph).
`sudo docker-compose up -d`

docker-compose.yml:
```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:v1.0.16
    volumes:
      - type: volume
        source: dgraph-1.0.13
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  server:
    image: dgraph/dgraph:v1.0.16
    volumes:
      - type: volume
        source: dgraph-1.0.13
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=server:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:v1.0.16
    volumes:
      - type: volume
        source: dgraph-1.0.13
        target: /dgraph
        volume:
          nocopy: true
    ports:
      - 8000:8000
    command: dgraph-ratel

volumes:
  # 1.0.16 has the same data format as 1.0.13
  dgraph-1.0.13:

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.50.0.0/16
```

- Expected behaviour and actual result.

got error in docker logs:

server_1  | I0715 17:15:10.451475       1 node.go:88] 423 tables out of 445 opened in 4m33.832s
[2019-07-15 10:15:10,697] INFO Stopping heartbeat thread [kafka.coordinator:base.py:_close_heartbeat_thread:730]
server_1  | I0715 17:15:12.794048       1 node.go:88] 426 tables out of 445 opened in 4m36.174s
server_1  | I0715 17:15:15.649198       1 node.go:88] 430 tables out of 445 opened in 4m39.029s
server_1  | I0715 17:15:18.769934       1 node.go:88] 434 tables out of 445 opened in 4m42.15s
server_1  | I0715 17:15:22.261058       1 node.go:88] 438 tables out of 445 opened in 4m45.641s
server_1  | I0715 17:15:26.979070       1 node.go:88] All 445 tables opened in 4m50.359s
server_1  | I0715 17:15:27.029023       1 node.go:88] Replaying file id: 4928 at offset: 1031622883
server_1  | I0715 17:15:27.443839       1 node.go:88] Replay took: 414.7866ms
server_1  | I0715 17:15:27.443968       1 node.go:88] Replaying file id: 4929 at offset: 0
server_1  | I0715 17:15:38.209951       1 node.go:88] Replay took: 10.765951875s
server_1  | I0715 17:15:38.210132       1 node.go:88] Replaying file id: 4930 at offset: 0
server_1  | I0715 17:15:39.852394       1 node.go:88] Replay took: 1.642230196s
**server_1  | 2019/07/15 17:15:39 Error while creating badger KV posting store error: unexpected end of JSON input**
**server_1  | failed to unmarshal discard stats**
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).populateDiscardStats
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:1449
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.(*valueLog).open
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/value.go:855
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.Open
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/db.go:317
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger.OpenManaged
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/dgraph-io/badger/managed_db.go:26
server_1  | github.com/dgraph-io/dgraph/edgraph.(*ServerState).initStorage
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:170
server_1  | github.com/dgraph-io/dgraph/edgraph.InitServerState
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/edgraph/server.go:77
server_1  | github.com/dgraph-io/dgraph/dgraph/cmd/alpha.run
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:465
server_1  | github.com/dgraph-io/dgraph/dgraph/cmd/alpha.init.1.func1
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/alpha/run.go:81
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).execute
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:702
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).ExecuteC
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:783
server_1  | github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra.(*Command).Execute
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/vendor/github.com/spf13/cobra/command.go:736
server_1  | github.com/dgraph-io/dgraph/dgraph/cmd.Execute
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/cmd/root.go:60
server_1  | main.main
server_1  | 	/tmp/go/src/github.com/dgraph-io/dgraph/dgraph/main.go:33
server_1  | runtime.main
server_1  | 	/usr/local/go/src/runtime/proc.go:200
server_1  | runtime.goexit
server_1  | 	/usr/local/go/src/runtime/asm_amd64.s:1337
