### ISSUE TITLE
eq-filter on indexed predicate returns empty result

### ISSUE THREAD

**Issue by lutzmoeller** [dgraph-io/dgraph#4778]
### What version of Dgraph are you using?
v1.1.1

### Have you tried reproducing the issue with the latest release?
Not yet, but there is no indication that this behaviour is known. We will check it with the update soon.

### What is the hardware spec (RAM, OS)?
Kubernetes v1.16.2
3 Replicas for alpha
3 Replicas for zero

### Steps to reproduce the issue (command/config used to run Dgraph).
Unfortunately I can't figure out how to get into this invalid state, but while working with the system (inserting, deleting, querying nodes) the following behavior occurs.

### Expected behaviour and actual result.
I'm using a filter with eq on an indexed predicate in a query.
The index on the predicate "status" is set to "hash" (but I also tried "exact" and the same problem occured after a while)

### Query 1:
```
{
		d(func: type(product-family)) @filter(eq(status, "active")) { 
			uid status
		}
}
```

The result I get is empty:
```
{
  "data": {
    "d": []
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 110898,
      "processing_ns": 4735834,
      "encoding_ns": 4100,
      "assign_timestamp_ns": 1704576,
      "total_ns": 6656807
    },
    "txn": {
      "start_ts": 48121
    },
    "metrics": {
      "num_uids": {
        "dgraph.type": 0,
        "status": 0,
        "uid": 0
      }
    }
  }
}
```
The curious thing is that I don't get any error. The result is just empty.

### Query 2:
While executing the query without the filter:
```
{
		d(func: type(product-family)) { 
			uid status
		}
}
```

I get the full result. As you can see, there are "status" fields with the value "active"
```
{
  "data": {
    "d": [
      {
        "uid": "0x4",
        "status": "active"
      },
      {
        "uid": "0x5",
        "status": "active"
      },
      {
        "uid": "0x6",
        "status": "inactive"
      }
 ... many more ...
    ]
  },
  "extensions": {
    "server_latency": {
      "parsing_ns": 94499,
      "processing_ns": 4573145,
      "encoding_ns": 33700,
      "assign_timestamp_ns": 1523982,
      "total_ns": 6380724
    },
    "txn": {
      "start_ts": 48124
    },
    "metrics": {
      "num_uids": {
        "dgraph.type": 0,
        "status": 3,
        "uid": 3
      }
    }
  }
}
```

### Query 3:
I can also use the following query to get what I want:
```
{  
var(func: type(product-family)) {all as uid}
var(func: uid(all)) { p1 as status }

d(func: uid(all)) @filter(eq(val(p1), "active")) { count(uid) } 
}
```

But probably at this query the eq is applied to the already loaded subset.

To fix the invalid behavior I just need to recreate the index (or set it to a different tokenizer) and everything works fine again.

I did not found any hint in the other issues or release notes, so I would be really glad if someone can support on this.
Thanks a lot

**Comment by MichelDiz** [comment]
@lutzmoeller can you share the steps to reproduce it? please.

**Comment by MichelDiz** [comment]
@lutzmoeller can you share the steps to reproduce it? please.

Update:
This seems to be related https://discuss.dgraph.io/t/query-based-on-eq-stopped-working-for-one-predicate/5939/14

I'm trying to reproduce this by myself. But I'm pretty sure that I won't be able to create a reproducible test.

**Comment by lutzmoeller** [comment]
@MichelDiz Yes, that sounds exactly like my issue. We have a similar data schema like mentioned there. Unfortunately, I can't tell when it's gonna break either. 

We are storing the data in persistent volumes. Maybe this could be some reason.
Anyway, here are our statefulset specs. I hope this helps on reproducing the issue. If you need any further information, please tell me.

Alpha:
```
spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
      initContainers:
        - name: dgraph-alpha-init
          image: 'docker.io/dgraph/dgraph:v1.1.1'
          command:
            - bash
            - '-c'
            - |
              trap "exit" SIGINT SIGTERM
              echo "Write to /dgraph/doneinit when ready."
              until [ -f /dgraph/doneinit ]; do sleep 2; done
          resources: {}
          volumeMounts:
            - name: datadir
              mountPath: /dgraph
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: dgraph-alpha
          image: 'docker.io/dgraph/dgraph:v1.1.1'
          command:
            - bash
            - '-c'
            - >
              set -ex

              dgraph alpha --my=$(hostname -f):7080 --lru_mb 2048 --zero
              $(ZERO_ADDRESS)
          ports:
            - name: grpc-intern
              containerPort: 7080
              protocol: TCP
            - name: http-alpha
              containerPort: 8080
              protocol: TCP
            - name: grpc-alpha
              containerPort: 9080
              protocol: TCP
          env:
            - name: ZERO_ADDRESS
              value: >- [...]
          resources:
            requests:
              memory: 100Mi
          volumeMounts:
            - name: datadir
              mountPath: /dgraph
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: [...]
                    app.kubernetes.io/name: dgraph-alpha
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
```

Zero: 
```
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/instance: [...]
      app.kubernetes.io/name: dgraph-zero
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: [...]
        app.kubernetes.io/name: dgraph-zero
    spec:
      volumes:
        - name: datadir
          persistentVolumeClaim:
            claimName: datadir
      containers:
        - name: dgraph-zero
          image: 'docker.io/dgraph/dgraph:v1.1.1'
          command:
            - bash
            - '-c'
            - |
              set -ex
              [[ `hostname` =~ -([0-9]+)$ ]] || exit 1
              ordinal=${BASH_REMATCH[1]}
              idx=$(($ordinal + 1))
              if [[ $ordinal -eq 0 ]]; then
                dgraph zero --my=$(hostname -f):5080 --idx $idx --replicas ${REPLICAS}
              else
                dgraph zero --my=$(hostname -f):5080 --peer $(PEER) --idx $idx --replicas ${REPLICAS}
              fi
          ports:
            - name: grpc-zero
              containerPort: 5080
              protocol: TCP
            - name: http-zero
              containerPort: 6080
              protocol: TCP
          env:
            - name: PEER
              value: >-[...]
            - name: REPLICAS
              value: '3'
          resources:
            requests:
              memory: 100Mi
          volumeMounts:
            - name: datadir
              mountPath: /dgraph
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 60
      dnsPolicy: ClusterFirst
      securityContext: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: [...]
                    app.kubernetes.io/name: dgraph-zero
                topologyKey: kubernetes.io/hostname
      schedulerName: default-scheduler
```
