### ISSUE TITLE
UNKNOWN: strconv.ParseInt: parsing - value out of range

### ISSUE THREAD

**Issue by calummoore** [dgraph-io/dgraph#5059]
### What version of Dgraph are you using?
v1.2.2

### Have you tried reproducing the issue with the latest release?
Yes

### What is the hardware spec (RAM, OS)?
2.8 GHz Intel Core i7
MacOS - Docker 
```
 dgraph:
    image: dgraph/standalone:v1.2.2
    volumes:
      - dgraph-data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
      - 8000:8000
    restart: on-failure
    environment:
      - DGRAPH_ALPHA_LRU_MB=2096
```

### Steps to reproduce the issue (command/config used to run Dgraph).

Schema:
```
<custom.user_id.number>: float @index(float) .
```

Mutation
```
{
set: [{
    'custom.user_id.number': 118430317093192000000,
    uid: '0xf4f2'
  }]
}
```

Error following mutation:
```
Error: 2 UNKNOWN: strconv.ParseInt: parsing "118430317093192000000": value out of range
    at Object.exports.createStatusError (/Users/calummoore/snapboard/code/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/calummoore/snapboard/code/node_modules/grpc/src/client_interceptors.js:1209:28)
    at InterceptingListener._callNext (/Users/calummoore/snapboard/code/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/calummoore/snapboard/code/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/calummoore/snapboard/code/node_modules/grpc/src/client_interceptors.js:847:24) {
  code: 2,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'strconv.ParseInt: parsing "118430317093192000000": value out of range'
}
```

If I make the property a string, then it works:
```
{
  "set": [{
    "uid": "0xf4f2",
    "custom.user_properties_id.number": "118430317093192000000"
  }]
}
```

### Expected behaviour and actual result.
No error
