### ISSUE TITLE
Dgraph v20.03.0 Regexp Not returning expected results

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/dgraph#5102]
## SUMMARY

Using a query like `regexp(name@en, /.*alien.*/i))` returns back an empty set.  This was discovered in the dgraph tour: https://dgraph.io/tour/search/3/#

## ENVIRONMENT

* Version: docker image `dgraph/dgraph:v20.03.0`
* System:  Docker Desktop v2.2.0.5 6GB running on host Mac OS 10.14.6

### STEP 1 - Env

```bash
docker-compose up -d
```

Compose File
```yaml
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph alpha --my=alpha:7080 --lru_mb=2048 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:${DGRAPH_VERSION}
    ports:
      - 8000:8000
    command: dgraph-ratel
```

### STEP 2 - Schema

Apply the Schema in:
* https://dgraph.io/tour/moredata/1/
* https://dgraph.io/tour/moredata/2/

### STEP 3 - Load Data

```bash
wget "https://github.com/dgraph-io/tutorial/blob/master/resources/1million.rdf.gz?raw=true" -O 1million.rdf.gz -q
docker cp ./1million.rdf.gz dgraph_zero_1:/tmp
docker exec -it dgraph_zero_1 dgraph live -f /tmp/1million.rdf.gz --alpha alpha:9080 --zero zero:5080 -c 1
```

### STEP 3 - Indexes

Apply Indexes from: https://dgraph.io/tour/search/1/

```
name: string @index(term, fulltext, trigram) @lang .
```

### STEP 4 - Run query

From: https://dgraph.io/tour/search/3/#

```
{
  aliens(func: regexp(name@en, /.*alien.*/i)) @cascade {
    name@en
    ~genre {
      name@en
      starring {
        performance.actor @filter(regexp(name@en,
          /(.*ali.*e.*n.*)|(.*a.*lie.*n.*)|(.*a.*l.*ien.*)/i)) {
          name@en
        }
      }
    }
  }
}
```

## EXPECTED BEHAVIOR

```javascript
{
  "data": {
    "aliens": [
      {
        "name@en": "Alien Film",
        "~genre": [
          {
            "name@en": "Mars Attacks!",
            "starring": [
              {
                "performance.actor": [
                  {
                    "name@en": "Natalie Portman"
                  }
                ]
              }
            ]
          }
        ]
      }
    ]
  }
/* ... */
}
```

## ACTUAL BEHAVIOR

```javascript
{
  "data": {
    "aliens": []
  }
/* ... */
}
```
## WORKAROUND

I modified the query and this worked:

```
{
  aliens(func: regexp(name@en, /.*ali.*e.*n.*/i)) @cascade {
    name@en
    ~genre {
      name@en
      starring {
        performance.actor @filter(regexp(name@en,
          /(.*ali.*e.*n.*)|(.*a.*lie.*n.*)|(.*a.*l.*ien.*)/i)) {
          name@en
        }
      }
    }
  }
}
```
