### ISSUE TITLE
Latest release is v20.03.0-beta.20200320?

### ISSUE THREAD

**Issue by ScottWallace** [dgraph-io/dgraph#5581]
### What version of Dgraph are you using?
That's what I'm trying to find out.

### Have you tried reproducing the issue with the latest release?
I presume.  Who can tell?

### What is the hardware spec (RAM, OS)?
Plenty of both.  Just installed minutes ago.

### Steps to reproduce the issue (command/config used to run Dgraph).
Install on docker with command: `docker-compose up -d` using this yml file:

```
version: "3.2"
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: always
    command: dgraph zero --my=zero:5080
  alpha:
    image: dgraph/dgraph:latest
    volumes:
      - /tmp/data:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: always
    command: dgraph alpha --my=alpha:7080 --lru_mb=6144 --zero=zero:5080
  ratel:
    image: dgraph/dgraph:latest
    ports:
      - 8000:8000
    command: dgraph-ratel
    restart: always
```

### Expected behaviour and actual result.
When running `http://[myipaddress]:8080/health`, the result is:

`[{"instance":"alpha","address":"alpha:7080","status":"healthy","group":"1","version":"v20.03.0-beta.20200320","uptime":6061605,"lastEcho":1591323890}]`

So, according to github, the latest release is v20.03.3, but my brand new install using `dgraph/dgraph:latest` shows v20.03.0-beta.20200320.

Does the latest still point to v20.03.0-beta.20200320, or was there a problem with the version number in the actual v20.03.3 (latest)?  Do I really have v20.03.3?
