### ISSUE TITLE
[QUESTION]: <Snapshot Isolation Testing>

### ISSUE THREAD

**Issue by seedoilz** [dgraph-io/dgraph#8952]
### Question.

# Snapshot Isolation Bug

## Environment

> Using Docker swarm to set up the Dgraph Cluster

There are 3 nodes in the cluster. The cluster is set on three servers based on the doc of the official website.

Docker version: 20.10.21

Dgraph version: 23.1.0(latest)

![image-20230816095836580](https://typora-tes.oss-cn-shanghai.aliyuncs.com/picgo/image-20230816095836580.png)

![image-20230816100011829](https://typora-tes.oss-cn-shanghai.aliyuncs.com/picgo/image-20230816100011829.png)

### docker-compose.yml

```yml
version: "3"
networks:
  dgraph:
services:
  zero_1:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == aws01
    command: dgraph zero --my=zero_1:5080 --replicas 3 --idx 1
  zero_2:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 5081:5081
      - 6081:6081
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == aws02
    command: dgraph zero -o 1 --my=zero_2:5081 --replicas 3 --peer zero_1:5080 --idx 2
  zero_3:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 5082:5082
      - 6082:6082
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == aws03
    command: dgraph zero -o 2 --my=zero_3:5082 --replicas 3 --peer zero_1:5080 --idx 3
  alpha_1:
    image: dgraph/dgraph:latest
    hostname: "alpha_1"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == aws01
    command: dgraph alpha --my=alpha_1:7080 --lru_mb=2048 --zero=zero_1:5080
  alpha_2:
    image: dgraph/dgraph:latest
    hostname: "alpha_2"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == aws02
    command: dgraph alpha --my=alpha_2:7081 --lru_mb=2048 --zero=zero_1:5080 -o 1
  alpha_3:
    image: dgraph/dgraph:latest
    hostname: "alpha_3"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == aws03
    command: dgraph alpha --my=alpha_3:7082 --lru_mb=2048 --zero=zero_1:5080 -o 2
  alpha_4:
    image: dgraph/dgraph:latest
    hostname: "alpha_4"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8083:8083
      - 9083:9083
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == aws04
    command: dgraph alpha --my=alpha_4:7083 --lru_mb=2048 --zero=zero_1:5080 -o 3
  alpha_5:
    image: dgraph/dgraph:latest
    hostname: "alpha_5"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8084:8084
      - 9084:9084
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == aws05
    command: dgraph alpha --my=alpha_5:7084 --lru_mb=2048 --zero=zero_1:5080 -o 4
  alpha_6:
    image: dgraph/dgraph:latest
    hostname: "alpha_6"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8085:8085
      - 9085:9085
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == aws06
    command: dgraph alpha --my=alpha_6:7085 --lru_mb=2048 --zero=zero_1:5080 -o 5
volumes:
  data-volume:
```

## How to send request

> Use http request to send request

### Code

```python
import ast
import json

import requests

url = "http://175.27.241.31:8080/mutate?commitNow=true"
headers = {'Content-Type': 'application/json'}


def generate_txn(ops):
    query = "query { "
    query_count = 0
    mutations = []
    for op in ops:
        if op["t"] == "r":
            query_count += 1
            q = "get%d(func: uid(%d)) { value } " % (query_count, op["k"])
            query += q
        else:
            mutations.append({
                "set": {
                    "uid": op["k"],
                    "value": op["v"]
                }
            })
    query += "}"
    if len(mutations) == 0:
        mutations.append({
            "set": {
                "fake_data": 233
            }
        })
    return {
        "query": query,
        "mutations": mutations
    }


def send_request(req_data):
    return requests.post(url, headers=headers, json=req_data)


def fetch_ts(resp_content):
    resp_data = ast.literal_eval(resp_content.decode("utf-8"))
    ts = resp_data["extensions"]["txn"]
    return ts["start_ts"], ts["commit_ts"]


def main():
    operations = [{"t": "w", "k": 745, "v": 697}, {"t": "w", "k": 853, "v": 74},
                  {"t": "r", "k": 853}, {"t": "r", "k": 745}]
    request_data = generate_txn(operations)
    response = send_request(request_data)
    start_ts, commit_ts = fetch_ts(response.content)
    txn = {
        "tid": "my unique id",
        "sid": "my session id",
        "ops": operations,
        "sts": {
            "p": start_ts,
            "l": 0
        },
        "cts": {
            "p": commit_ts,
            "l": 0
        }
    }
    print(json.dumps(txn, indent=4))


if __name__ == '__main__':
    main()
```

### How to generate the test cases

We use dbcop to generate test cases to do tests on Dgraph.

## Bug

When we use our own algorithm to test the snapshot Isolation, we find that most of the transactions break the snapshot isolation. 

I think that our own algorithm has no problem. 

So, my question is that which step I have taken is wrong? Thank you in advance.

**Comment by mangalaman93** [comment]
Hi @seedoilz, Could you elaborate how you identified that snapshot isolation is violated?

**Comment by seedoilz** [comment]
It is a timestamp-based determination method. All transactions are sorted in ascending order by commit timestamps. Then iterates through each transaction and, based on its start timestamps, determines which committed transactions it should have read, checking for consistency with the data it actually read. It also checks to see if concurrent transactions have write conflicts.
We are working on a paper on this, but it's only in draft form at the moment, so if you don't mind and are interested, we'd be happy to share it.

**Comment by mangalaman93** [comment]
If you could send across a way to reproduce the issue, we are happy to look into it. We saw something like this before too https://github.com/dgraph-io/dgraph/issues/8146 but later found out that the issue was with the application code.

**Comment by seedoilz** [comment]
What you need to do is to download the [[json file](https://box.nju.edu.cn/f/64a49141b4e44368bf41/)](https://box.nju.edu.cn/f/64a49141b4e44368bf41/) here and clone this [[code](https://github.com/Tsunaou/dbcdc-runner)](https://github.com/Tsunaou/dbcdc-runner). Then you need to set up the environment including Leiningen and Java (What **Jepsen** needs). Then you can run the following code in root directory of the code. (replacing the **${dbcop-workload-path}** with **the path of that json file**).

```shell
lein run test-all -w rw \
--txn-num 120000 \
--time-limit 43200 \
-r 10000 \
--node dummy-node \
--isolation snapshot-isolation \
--expected-consistency-model snapshot-isolation \
--nemesis none \
--existing-postgres \
--no-ssh \
--database dgraph \
--dbcop-workload-path ${dbcop-workload-path} \
--dbcop-workload
```

**Comment by mangalaman93** [comment]
`--lru_mb` is an old parameter. What version of Dgraph are you using? The compose file that you are using looks really old to me.

**Comment by seedoilz** [comment]
Sorry. Actually this compose file is not the one I used. However, I accidentally deleted my compose file. But my compose file is based on the one I gave. So I think it is not a big deal.

**Comment by seedoilz** [comment]
This compose file is the one I was using. You could change a bit (node name) and use it.
```
version: "3.2"
networks:
  dgraph:
services:
  zero:
    image: dgraph/dgraph:latest
    volumes:
      - data-volume:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == VM-0-7-tencentos
    command: dgraph zero --my=zero:5080 --replicas 3
  alpha1:
    image: dgraph/dgraph:latest
    hostname: "alpha1"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    networks:
      - dgraph
    deploy:
      placement:
        constraints:
          - node.hostname == VM-0-7-tencentos
    command: dgraph alpha --my=alpha1:7080 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1 --zero=zero:5080
  alpha2:
    image: dgraph/dgraph:latest
    hostname: "alpha2"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8081:8081
      - 9081:9081
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == VM-0-12-tencentos
    command: dgraph alpha --my=alpha2:7081 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1 --zero=zero:5080 -o 1
  alpha3:
    image: dgraph/dgraph:latest
    hostname: "alpha3"
    volumes:
      - data-volume:/dgraph
    ports:
      - 8082:8082
      - 9082:9082
    networks:
      - dgraph
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == VM-0-14-tencentos
    command: dgraph alpha --my=alpha3:7082 --security whitelist=10.0.0.0/8,172.0.0.0/8,192.168.0.0/16,127.0.0.1 --zero=zero:5080 -o 2
volumes:
  data-volume:
```
